displayName: Custom IndiGo .NET
description: Custom IndiGo .NET stack with .NET Core SDK 6, Runtime, C# Language Support and Debugger
tags:
  - .NET
  - C#
  - .NET SDK
  - .NET Runtime
  - Netcoredbg
  - Omnisharp
  - UBI8
icon: /images/type-dotnet.svg
links:
  v2: https://github.com/bbalakriz/dotnet-web-simple-devspaces
  devWorkspaces:
    che-incubator/che-idea/latest: /devfiles/TP__indigo__dotnet-web-simple/devworkspace-che-idea-latest.yaml
    che-incubator/che-code/insiders: /devfiles/TP__indigo__dotnet-web-simple/devworkspace-che-code-insiders.yaml
    che-incubator/che-code/latest: /devfiles/TP__indigo__dotnet-web-simple/devworkspace-che-code-latest.yaml
